# Generated by Django 4.2.7 on 2024-01-10 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkInfrastructureDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('type', models.CharField(choices=[('SWITCH', 'Switch'), ('ROUTER', 'Router'), ('ACCESS_POINT', 'Access Point')], max_length=20)),
                ('number_of_ports', models.IntegerField(help_text='Number of ports (for switches and routers)')),
            ],
        ),
        migrations.CreateModel(
            name='PatchPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number_of_ports', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VLAN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('vlan_id', models.IntegerField(unique=True)),
                ('vlan_color', models.CharField(help_text='Enter the color in HEX format (e.g., #FF5733)', max_length=7)),
                ('gateway', models.GenericIPAddressField(help_text='Enter the gateway IP address')),
                ('dhcp_range', models.CharField(help_text='Enter the DHCP range (e.g., 192.168.1.100-192.168.1.200)', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SSID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssid_name', models.CharField(max_length=100)),
                ('vlan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.vlan')),
            ],
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_number', models.IntegerField()),
                ('is_trunk', models.BooleanField(default=False)),
                ('active_vlans', models.ManyToManyField(blank=True, to='home.vlan')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='home.networkinfrastructuredevice')),
            ],
        ),
        migrations.CreateModel(
            name='PatchPanelPort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_number', models.IntegerField()),
                ('patch_panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='home.patchpanel')),
            ],
        ),
        migrations.AddField(
            model_name='networkinfrastructuredevice',
            name='vlan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.vlan'),
        ),
        migrations.CreateModel(
            name='ClientDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('type', models.CharField(choices=[('SERVER', 'Server'), ('PRINTER', 'Printer'), ('PC', 'PC'), ('CAMERA', 'Camera')], max_length=20)),
                ('connection_type', models.CharField(blank=True, choices=[('WIRELESS', 'Wireless'), ('WIRED_PATCH', 'Wired to Patch Panel'), ('WIRED_SWITCH', 'Wired to Switch/Router')], max_length=15, null=True)),
                ('patch_panel_port', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.patchpanelport')),
                ('ssid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.ssid')),
                ('switch_router_port', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.port')),
                ('vlan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.vlan')),
            ],
        ),
    ]
