# Generated by Django 4.2.7 on 2024-01-17 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdevice',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.site'),
        ),
        migrations.AddField(
            model_name='networkinfrastructuredevice',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.site'),
        ),
        migrations.AddField(
            model_name='patchpanel',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.site'),
        ),
        migrations.AddField(
            model_name='patchpanelport',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.site'),
        ),
        migrations.AddField(
            model_name='port',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.site'),
        ),
        migrations.AddField(
            model_name='ssid',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.site'),
        ),
        migrations.AddField(
            model_name='vlan',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.site'),
        ),
    ]
