# Generated by Django 4.2.7 on 2024-01-18 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_network_remove_clientdevice_vlan_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='network',
            old_name='network_id',
            new_name='vlan_id',
        ),
        migrations.AlterUniqueTogether(
            name='network',
            unique_together={('site', 'vlan_id')},
        ),
    ]
