# Generated by Django 4.2.7 on 2024-01-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_network_id_network_vlan_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='dhcp_end',
            field=models.GenericIPAddressField(blank=True, help_text='Enter the end of the DHCP range (e.g., 192.168.1.200)', null=True),
        ),
        migrations.AddField(
            model_name='network',
            name='dhcp_server',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='network',
            name='dhcp_start',
            field=models.GenericIPAddressField(blank=True, help_text='Enter the start of the DHCP range (e.g., 192.168.1.100)', null=True),
        ),
        migrations.AddField(
            model_name='network',
            name='netmask',
            field=models.IntegerField(choices=[(30, '/30'), (29, '/29'), (28, '/28'), (27, '/27'), (26, '/26'), (25, '/25'), (24, '/24'), (23, '/23'), (22, '/22'), (21, '/21'), (20, '/20'), (19, '/19'), (18, '/18'), (17, '/17'), (16, '/16'), (15, '/15'), (14, '/14'), (13, '/13'), (12, '/12'), (11, '/11'), (10, '/10'), (9, '/9'), (8, '/8')], default=24),
        ),
        migrations.AddField(
            model_name='network',
            name='primary_dns',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='network',
            name='secondary_dns',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='network',
            name='dhcp_range',
            field=models.CharField(blank=True, help_text='Enter the DHCP range (e.g., 192.168.1.100-192.168.1.200)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='network',
            name='gateway',
            field=models.GenericIPAddressField(blank=True, help_text='Enter the gateway IP address', null=True),
        ),
    ]
