# Generated by Django 4.2.7 on 2024-01-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_network_dhcp_end_network_dhcp_server_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='broadcast_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='network',
            name='ip_range',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='network',
            name='netmask_formatted',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='network',
            name='usable_ips',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
